# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class SshAgentMux < Formula
  desc "Combines multiple agents' keys into a single agent"
  homepage "https://github.com/overhacked/ssh-agent-mux"
  url "https://github.com/overhacked/ssh-agent-mux/archive/refs/tags/v0.1.5.tar.gz"
  version "0.1.5"
  sha256 "55cc828c65b7ae1d68a1c77f03a1959a410508a613636b93284b77a228957068"
  license "BSD-3-Clause"

  on_macos do
    on_intel do
      url "https://github.com/overhacked/ssh-agent-mux/releases/download/v0.1.5/ssh-agent-mux-0.1.5-darwin-amd64.tar.gz"
      sha256 "3ac6239dd081b9f232a1e82b95c93941704f5287f85cee80ef29f37a4372e000"
    end

    on_arm do
      url "https://github.com/overhacked/ssh-agent-mux/releases/download/v0.1.5/ssh-agent-mux-0.1.5-darwin-arm64.tar.gz"
      sha256 "8727a8f0903a32356b83b6718f31e18fe07b83393cf54e70d09e888b4b90b1ad"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/overhacked/ssh-agent-mux/releases/download/v0.1.5/ssh-agent-mux-0.1.5-linux-amd64.tar.gz"
      sha256 "009a185af10fc45f0c8a297b57a2728d4ac47efed8d5611731e8ee1c8da49172"
    end

    on_arm do
      url "https://github.com/overhacked/ssh-agent-mux/releases/download/v0.1.5/ssh-agent-mux-0.1.5-linux-arm64.tar.gz"
      sha256 "a850493d4c60ca8782fd66ea5674f6e41efb682f90ed351bba6225f46799075c"
    end
  end

  def install
    bin.install "ssh-agent-mux"
  end

  test do
    agent_stdout = shell_output(
        %Q(sock="#{testpath}/ssh-agent-mux.sock";) \
        + %Q( ssh-agent-mux --log-level info --config /dev/null --listen "$sock" &) \
        + %Q( until [ -e "$sock" ]; do sleep 0.1; done;) \
        + %Q( kill %1; wait %1)
    )
    assert_match "Starting agent", agent_stdout
    assert_match "Exiting on SIGTERM", agent_stdout
  end
end
