# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class SshAgentMux < Formula
  desc "Ssh-agent-mux combines multiple agents' keys into a single agent"
  homepage "https://github.com/overhacked/ssh-agent-mux"
  url "https://github.com/overhacked/ssh-agent-mux/archive/refs/tags/v0.1.4.tar.gz"
  version "0.1.4"
  sha256 "1ea4fe22c39a6486163cef027af331b79810cf7068c564cafbbeb0a68021d496"
  license "BSD-3-Clause"

  on_macos do
    on_intel do
      url "https://github.com/overhacked/ssh-agent-mux/releases/download/v0.1.4/ssh-agent-mux-0.1.4-darwin-amd64.tar.gz"
      sha256 "002c75698343d6c5dca1182bfcd108fb6206da7def9519019bf5e39e08119b2e"
    end

    on_arm do
      url "https://github.com/overhacked/ssh-agent-mux/releases/download/v0.1.4/ssh-agent-mux-0.1.4-darwin-arm64.tar.gz"
      sha256 "1ecda6b0dbcaac29bcc3a530d721b1b5ddffefae2d50badcab6a15f3d8655c95"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/overhacked/ssh-agent-mux/releases/download/v0.1.4/ssh-agent-mux-0.1.4-linux-amd64.tar.gz"
      sha256 "6a0b7df8db7389cf872753e8e25a7fcbf9cc27e979f74b83a310fcfb4ec649fa"
    end

    on_arm do
      url "https://github.com/overhacked/ssh-agent-mux/releases/download/v0.1.4/ssh-agent-mux-0.1.4-linux-arm64.tar.gz"
      sha256 "1a4162c878d110af89d34b8594fc27aff4cc00a2d56fc5191d0e563008eaa0f8"
    end
  end

  def install
    bin.install "ssh-agent-mux"
  end

  test do
    agent_stdout = shell_output(%Q{sock="#{testpath}/ssh-agent-mux.sock"; ssh-agent-mux --log-level info --config /dev/null --listen "$sock" & until [ -e "$sock" ]; do sleep 0.1; done; kill %1; wait %1})
assert_match "Starting agent", agent_stdout
assert_match "Exiting on SIGTERM", agent_stdout
  end
end
