# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class SshAgentMux < Formula
  desc "Ssh-agent-mux combines multiple agents' keys into a single agent, allowing you t"
  homepage "https://github.com/overhacked/ssh-agent-mux"
  url "https://github.com/overhacked/ssh-agent-mux/archive/refs/tags/v0.1.2.tar.gz"
  version "0.1.2"
  sha256 "864a264d776777f95b52c470f543e38740aa85be489b0c3d183142220882fe87"
  license "BSD-3-Clause"

  on_macos do
    on_intel do
      url "https://github.com/overhacked/ssh-agent-mux/releases/download/v0.1.2/ssh-agent-mux-0.1.2-darwin-amd64.tar.gz"
      sha256 "49634da083492a242dea2f8302251421bd07f72a5522b85eda9463030de26324"
    end

    on_arm do
      url "https://github.com/overhacked/ssh-agent-mux/releases/download/v0.1.2/ssh-agent-mux-0.1.2-darwin-arm64.tar.gz"
      sha256 "4b1e35a6b9c17014055b81d6cac056b7f606063342309d60375c45987b3ae74f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/overhacked/ssh-agent-mux/releases/download/v0.1.2/ssh-agent-mux-0.1.2-linux-amd64.tar.gz"
      sha256 "04c3aa2b50b31daf5d19a18f1e0b5778839e6cea088cbeb367c8d5912900cd7f"
    end

    on_arm do
      url "https://github.com/overhacked/ssh-agent-mux/releases/download/v0.1.2/ssh-agent-mux-0.1.2-linux-arm64.tar.gz"
      sha256 "e6dc9c58cb7959fb2c194572bd2aafaed285c56f8c2c7e223fefc2e59d346348"
    end
  end

  def install
    bin.install "ssh-agent-mux"
  end

  test do
    agent_stdout = shell_output(%Q{sock="#{testpath}/ssh-agent-mux.sock"; ssh-agent-mux --log-level info --config /dev/null --listen "$sock" & until [ -e "$sock" ]; do sleep 0.1; done; kill %1; wait %1})
assert_match %r%Starting agent%, agent_stdout
assert_match %r%Exiting on SIGTERM%, agent_stdout
  end
end
